version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
volumes:
  my-db: